apiVersion: apps/v1
kind: Deployment
metadata:
  name: plasmid-js-deployment
  namespace: {{NAMESPACE}}
spec:
  selector:
    matchLabels:
      app: plasmid-js-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: plasmid-js-deployment
    spec:
      containers:
        - name: plasmid-js-container
          image: {{IMAGE_NAME}}
          ports:
            - name: plasmid-js-port
              containerPort: 80
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: plasmid-js-service
  namespace: {{NAMESPACE}}
  labels:
    app: plasmid-js-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: plasmid-js-port
      protocol: TCP
  selector:
    app: plasmid-js-deployment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plasmid-js
  namespace: {{NAMESPACE}}
spec:
  rules:
    - host: plasmid-js{{ENV_SUFFIX}}.mydna.codes
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: analysis-service
                port:
                  number: 80